### ISSUE TITLE
Kein "Siehe Auch" wenn der einzige eintrag "Index" ist

### ISSUE THREAD

**Issue by makefu** [KurtPfeifle/shackspace-glossar#1]
ssia

**Comment by pdfkungfoo** [comment]
Vieles Einträge sind noch weitgehend leer und bestehen daher weitgehend noch aus Struktur-Platzhaltern. Auch die drei Indexe bleiben nicht auf Dauer so. Sie dienen nur einem schnelleren Überblick, um "leere" bzw. "befüllte" Einträge effizienter finden zu können.
